name: Pull Request workflow

on:
  pull_request:
    branches:
      - develop
jobs:
  branch_naming:
    runs-on: ubuntu-20.04
    steps:
      - name: Check branch naming
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z][a-z-0-9]*[a-z0-9])'
          allowed_prefixes: 'feat,fix,devops,bump'
          ignore: develop
          min_length: 5
          max_length: 30
  lint:
    runs-on: ubuntu-20.04
    needs: branch_naming
    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          recursive: true
          dockerfile: "Dockerfile"

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install eslint
        run: npm install -g eslint

      - name: Run ESLint
        run: npm run lint