name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-arc-docker-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(?<version>.*)"

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish arc:${{ steps.tagName.outputs.version }}
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: arc
          docker-image-tag: ${{ steps.tagName.outputs.version }}
          dockerfile-path: ./Dockerfile
          build-context: ./

